import { parseSnapshotReadResponse } from "../../api/contract";

export const DEMO_RESPONSE = parseSnapshotReadResponse({
  snapshot: {
    schema_version: 1,
    boot_id: "5a1e6a9f-a31d-4f12-9a8e-7f8c2601a001",
    sequence: 42,
    generated_at: "2026-09-26T13:25:00-03:00",
    collector: {
      status: "monitoring",
      last_collection_at: "2026-09-26T13:25:00-03:00",
    },
    port: {
      name: "Porto do Pecém",
    },
    vessels: [
      {
        name: "ATLANTIC DAWN",
        imo: "9487654",
        status: "ATRACANDO",
        section: "FUNDEADO",
        berth: 2,
        side: "BB",
        eta: "26/09 12:40",
        etb_ets: "26/09 13:30",
        pob: "13:10",
        flag: "Panamá",
        origin_port: "Roterdã",
        irin: "3EAA7",
        agency: "Atlântica Shipping",
        tugs: "T-01, T-04",
      },
      {
        name: "OCEAN STAR",
        imo: "9321456",
        status: "DESATRACANDO",
        section: "ATRACADO",
        berth: 7,
        side: "BE",
        eta: "25/09 22:15",
        etb_ets: "26/09 13:45",
        pob: "13:18",
        flag: "Libéria",
        origin_port: "Houston",
        irin: "D5OS9",
        agency: "Mar do Norte",
        tugs: "T-02, T-05",
      },
      {
        name: "MERIDIAN SKY",
        imo: "9567890",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 5,
        side: "BB",
        eta: "26/09 03:30",
        etb_ets: "26/09 18:20",
        pob: "04:05",
        flag: "Malta",
        origin_port: "Santos",
        irin: "9HMS4",
        agency: "Pecém Marine",
        tugs: null,
      },
      {
        name: "BLUE HORIZON",
        imo: "9712345",
        status: "FUNDEADO",
        section: "FUNDEADO",
        berth: 4,
        side: null,
        eta: "26/09 09:50",
        etb_ets: "26/09 16:10",
        pob: null,
        flag: "Bahamas",
        origin_port: "Cartagena",
        irin: "C6BH2",
        agency: "Oceanic",
        tugs: null,
      },
      {
        name: "PACIFIC WIND",
        imo: "9654321",
        status: "PREVISTO",
        section: "PREVISTO",
        berth: 9,
        side: "BB",
        eta: "26/09 17:00",
        etb_ets: "26/09 17:40",
        pob: null,
        flag: "Singapura",
        origin_port: "Las Palmas",
        irin: "9VPW8",
        agency: "Global Port",
        tugs: null,
      },
      {
        name: "CEARA EXPRESS",
        imo: "9234567",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 1,
        side: "BE",
        eta: "25/09 20:10",
        etb_ets: "27/09 01:15",
        pob: "20:42",
        flag: "Brasil",
        origin_port: "Suape",
        irin: "PPCE",
        agency: "Costa Nordeste",
        tugs: null,
      },
      {
        name: "NORTH SEA",
        imo: "9010003",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 3,
        side: "BB",
        eta: "26/09 05:20",
        etb_ets: "27/09 03:30",
        pob: "05:45",
        flag: "Marshall Islands",
        origin_port: "Antuérpia",
        irin: "V7NS3",
        agency: "Demo Marine",
        tugs: null,
      },
      {
        name: "SEA VOYAGER",
        imo: "9010004",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 4,
        side: "BE",
        eta: "26/09 06:15",
        etb_ets: "27/09 04:10",
        pob: "06:42",
        flag: "Panamá",
        origin_port: "Cartagena",
        irin: "3ESV4",
        agency: "Demo Marine",
        tugs: null,
      },
      {
        name: "PORTO BRASIL",
        imo: "9010006",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 6,
        side: "BB",
        eta: "26/09 07:40",
        etb_ets: "27/09 05:20",
        pob: "08:05",
        flag: "Brasil",
        origin_port: "Santos",
        irin: "PPPB6",
        agency: "Demo Marine",
        tugs: null,
      },
      {
        name: "GLOBAL TRADER",
        imo: "9010008",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 8,
        side: "BE",
        eta: "26/09 08:35",
        etb_ets: "27/09 06:10",
        pob: "09:00",
        flag: "Libéria",
        origin_port: "Houston",
        irin: "D5GT8",
        agency: "Demo Marine",
        tugs: null,
      },
      {
        name: "PACIFIC BERTH",
        imo: "9010009",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 9,
        side: "BB",
        eta: "26/09 09:25",
        etb_ets: "27/09 07:00",
        pob: "09:50",
        flag: "Singapura",
        origin_port: "Las Palmas",
        irin: "9VPB9",
        agency: "Demo Marine",
        tugs: null,
      },
      {
        name: "FORTALEZA SPIRIT",
        imo: "9010010",
        status: "ATRACADO",
        section: "ATRACADO",
        berth: 10,
        side: "BE",
        eta: "26/09 10:10",
        etb_ets: "27/09 08:30",
        pob: "10:35",
        flag: "Brasil",
        origin_port: "Suape",
        irin: "PPFS0",
        agency: "Demo Marine",
        tugs: null,
      },
    ],
    weather: {
      consulted_at: "2026-09-26T13:24:00-03:00",
      observed_at: "2026-09-26T13:20:00-03:00",
      air_temperature_c: 29.4,
      humidity_pct: 71,
      weather_code: 1,
      wind_speed_kn: 15.2,
      wind_direction_deg: 96,
      wind_gust_kn: 20.1,
      visibility_m: 10000,
      precipitation_mm: 0,
    },
    marine: {
      consulted_at: "2026-09-26T13:24:00-03:00",
      observed_at: "2026-09-26T13:00:00-03:00",
      wave_height_m: 1.3,
      wave_direction_deg: 88,
      wave_period_s: 7.6,
      swell_height_m: 0.9,
      swell_direction_deg: 75,
      swell_period_s: 9.1,
      sea_temperature_c: 28.1,
      current_kn: 0.7,
      current_direction_deg: 110,
    },
    recent_maneuvers: {
      active: [
        {
          id: "demo-arrival-atlantic",
          type: "ATRACACAO",
          vessel_name: "ATLANTIC DAWN",
          berth: 2,
          pob: "13:10",
          status: "ACTIVE",
          detected_at: "2026-09-26T13:08:00-03:00",
          completed_at: null,
        },
        {
          id: "demo-departure-ocean",
          type: "DESATRACACAO",
          vessel_name: "OCEAN STAR",
          berth: 7,
          pob: "13:18",
          status: "ACTIVE",
          detected_at: "2026-09-26T13:16:00-03:00",
          completed_at: null,
        },
      ],
      completed: [
        {
          id: "demo-completed-1",
          type: "ATRACACAO",
          vessel_name: "MERIDIAN SKY",
          berth: 5,
          pob: "04:05",
          status: "COMPLETED",
          detected_at: "2026-09-26T03:52:00-03:00",
          completed_at: "2026-09-26T04:32:00-03:00",
        },
        {
          id: "demo-completed-2",
          type: "DESATRACACAO",
          vessel_name: "NORDIC SUN",
          berth: 3,
          pob: "08:20",
          status: "COMPLETED",
          detected_at: "2026-09-26T08:18:00-03:00",
          completed_at: "2026-09-26T08:49:00-03:00",
        },
        {
          id: "demo-completed-3",
          type: "ATRACACAO",
          vessel_name: "CEARA EXPRESS",
          berth: 1,
          pob: "20:42",
          status: "COMPLETED",
          detected_at: "2026-09-25T20:38:00-03:00",
          completed_at: "2026-09-25T21:06:00-03:00",
        },
      ],
    },
  },
  meta: {
    received_at: "2026-09-26T13:25:03-03:00",
    age_seconds: 3,
    collector_online: true,
    stale_after_seconds: 120,
  },
});
